Update CONTRIBUTING.md broken links
git-bug/git-bug pull request #1276
Opened 2024-10-04 00:29 UTC by sparr

I'm not sure why this file uses the footnote-like markdown link syntax, but I tried to follow it when fixing the "without nix" link. I also removed the "how to clone" link that goes nowhere; maybe it was from an old version of the doc?

2025-01-02 03:57 UTC, sparr commented
This should still be reviewed and merged

2025-04-07 03:31 UTC, sudoforge requested changes

2025-04-07 03:31 UTC, sudoforge commented on CONTRIBUTING.md
> +[install/install-direnv-without-nix]: #user-content-install-direnv-without-nix
```suggestion
[install/install-direnv-without-nix]: #install-direnv-without-nix
```

i'm not quite sure where the `user-content` bit comes from (github's preview ui, maybe?); the above suggestion should work.

2025-05-05 23:31 UTC, sudoforge commented
Thanks for the contribution, @sparr! This was addressed in 96c7a111a3cb075b5ce485f709c3eb82da121a50, which brought on many changes to the documentation (and is why i held off on this).

2025-05-05 23:31 UTC, closed without merging