commands: add a command to export bugs as raw operations (replacement for PR# 501)
git-bug/git-bug pull request #1291
Opened 2024-11-03 18:44 UTC by mcepl

Replaces: #501

2025-04-08 06:29 UTC, mcepl commented
ping

2025-04-25 01:05 UTC, sudoforge commented
whenever you're interested in getting this reviewed, feel free to mark it as "ready" instead of a "draft".

2025-04-28 08:40 UTC, mcepl commented
I run `go run github.com/99designs/gqlgen` on this, which helped: the branch actually builds, but apparently it broke plenty of tests. Any ideas?

2025-04-29 01:58 UTC, sudoforge commented
The failures you got here (at least after 5582114) related to the time offset being invalid are due to the upgrade performed in this tree from `golang.org/x/time:v0.3.0` to `golang.org/x/time:v0.11.0`.

Rebasing on top of edbd105cfd42d05b2736746acf041f3fadea6e74 (`HEAD` as of this comment) will resolve that error for you.

2025-05-12 18:49 UTC, sudoforge requested changes
thanks for this! sorry it took a while to review.

generally speaking, the addition of the `export` command seems okay, but this change seems to have introduced a lot of noise (unecessary changes), and most critically, **some generated content is incorrectly referring to the older verb-driven CLI -- commands that do not exist**.

PTAL - if you [follow the contributor onboarding docs](https://github.com/git-bug/git-bug/blob/master/CONTRIBUTING.md) to activate the developer shell, you can be sure that you are using the correct version of `go` for this project.

i'd also like to see some unit tests added in for this.

---

> I run `go run github.com/99designs/gqlgen` on this, which helped: the branch actually builds, but apparently it broke plenty of tests. Any ideas?

Your usage of `go run` here is doing two things that are undesired:

- using your local version of go, which is not aligned with the version of go defined in the developer shell (well, i'm assuming this because the `go` directive was changed)
- pulling in and executing the latest version of `github.com/99designs/gqlgen`

2025-05-12 18:49 UTC, sudoforge commented on commands/export.go
> +		Example: `See ls`,
This should be an example of running the command, e.g.:

```suggestion
		Example: `git bug bug export`,
```

2025-05-12 18:49 UTC, sudoforge commented on commands/export.go
> +	// FIXME we are throwing away opts!
this seems important :)

2025-05-12 18:49 UTC, sudoforge commented on commands/root.go
> +	// undefined cmd.AddCommand(newTitleCommand(env))
generally speaking, i'm not a fan of adding commented code in version controlled files.

2025-05-12 18:49 UTC, sudoforge commented on doc/md/git-bug.md
> +* [git-bug webui](git-bug_webui.md)	 - Launch the web UI.
a lot of these don't exist.

2025-05-12 18:49 UTC, sudoforge commented on doc/man/git-bug.1
> +\fBgit\-bug\-add(1)\fP, \fBgit\-bug\-bridge(1)\fP, \fBgit\-bug\-commands(1)\fP, \fBgit\-bug\-comment(1)\fP, \fBgit\-bug\-deselect(1)\fP, \fBgit\-bug\-export(1)\fP, \fBgit\-bug\-label(1)\fP, \fBgit\-b
this generated content is incorrect.

2025-05-12 18:49 UTC, sudoforge commented on go.mod
> +go 1.23.8
why are we bumping the `go` directive here?

2025-05-12 18:49 UTC, sudoforge commented on go.mod
i don't think we ned to bump these deps for your change, do we?

2025-05-13 20:01 UTC, mcepl commented on doc/man/git-bug.1
> +\fBgit\-bug\-add(1)\fP, \fBgit\-bug\-bridge(1)\fP, \fBgit\-bug\-commands(1)\fP, \fBgit\-bug\-comment(1)\fP, \fBgit\-bug\-deselect(1)\fP, \fBgit\-bug\-export(1)\fP, \fBgit\-bug\-label(1)\fP, \fBgit\-b
manpage removed

2025-05-13 20:21 UTC, mcepl commented
Leaving this PR as it is. I don’t have time to play with more of this (The Real Life™ attacks) and even less I have time to play with nix. Continue with this, let it die, whatever.

2025-05-15 03:13 UTC, sudoforge commented
> Leaving this PR as it is. I don’t have time to play with more of this (The Real Life™ attacks) and even less I have time to play with nix. Continue with this, let it die, whatever.

sorry to hear that. if you ran into any specific issues with nix due to missing documentation in `//:CONTRIBUTING.md`, feel free to shoot me a message in whatever way is convenient so that i can update that.

i'm closing this for now, as without tests, it won't be merged in. i may revisit this in the future.

if anybody else wants to use this as the basis for implementing this feature, you can checkout this tree by running:

```
$ git fetch https://github.com/git-bug/git-bug.git refs/pull/1291/head
$ git checkout FETCH_HEAD
```

2025-05-15 03:13 UTC, closed without merging