Implement comment deletion feature
git-bug/git-bug pull request #946
Opened 2022-12-09 15:35 UTC by mendelmaleh

Fixes #939, only in termui for now. I mostly followed the edit implementation, let me know what can be improved.

2023-01-04 15:36 UTC, MichaelMure commented
hey @mendelmaleh, sorry for the delay. Large changes happened in git-bug core, and we are currently trying to catch bugs that came out of it. I'll get to your PR at some point.

2023-03-04 12:36 UTC, MichaelMure commented on entities/bug/timeline.go
> +	return c.History[len(c.History)-1].Author
That doesn't seem robust enough. What if something else happen after deleting? At the moment, it seems like only the local termui would prevent that. Going further, someone running another version of git-bug might make more change on that deleted comment.

We also need to decide what is the semantic to enforce here. If a comment is deleted, do we make no-op any further change? Do we accept them and gracefully handle that (as in, AddComment+DeleteComment+EditComment+UndeleteComment would show the modified comment). I'd go for the latter.

2023-03-04 12:38 UTC, MichaelMure requested changes
Pretty good code quality, thanks.
We need to figure out how to deal with the problem in my comment though. I can't merge like that as it could lead to issues.

2024-11-02 08:07 UTC, MichaelMure commented
Not stale

On Sat, Nov 2, 2024, 4:27 AM github-actions[bot] ***@***.***>
wrote:

> This bot triages pull requests in order to help the maintainers
> identify what needs attention, according to the following lifecycle
> rules:
>
>    - After 90 days of inactivity, lifecycle/stale is applied
>    - After 90 days of inactivity since lifecycle/stale was applied,
>    lifecycle/rotten is applied
>
> *This bot will not automatically close stale pull requests.*
>
> To remove the stale status, you can:
>
>    - Remove the stale label from this pull request
>    - Comment on this issue
>    - Close this issue
>    - Offer to help out with triage and code review
>
> ------------------------------
>
> To avoid automatic lifecycle management of this pull request, add
> lifecycle/frozen.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/git-bug/git-bug/pull/946#issuecomment-2452831438>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACH6DPY3W6K2X3YJZJ3DHLZ6RBCVAVCNFSM6AAAAABRBKC4SOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDINJSHAZTCNBTHA>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2025-04-07 04:21 UTC, closed without merging

2025-04-07 04:21 UTC, sudoforge commented
i'm going to close this for now to help keep the active board clean. if you wish to work on this tree in the future, you can always check it out like so:

```
$ git fetch https://github.com/git-bug/git-bug.git refs/pull/946/head
$ git checkout FETCH_HEAD
```